version: '3'
services:
  frontend:
    image: nginx
    depends_on: backend
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./map.html:/var/www/chatmap/index.html
  backend:
    build:
      context: .
    volumes:
      - ./storage:/app/storage
